import { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { ApiError } from '@/core/http';
import { can } from '@/core/permissions';
import { useNetworkStatus } from '@/core/query';
import { useSession } from '@/core/session';
import { AccessDeniedState, AppButton, ErrorState, LoadingState, OfflineBanner, Screen, TextField } from '@/shared';
import { colors, spacing, typography } from '@/shared/theme';
import { useCloseCashRegister, useCurrentCashRegister, useOpenCashRegister, type CashRegisterSnapshot } from '../application/cash';
const money = (value: string) => /^\d+(\.\d{1,2})?$/.test(value.trim()) ? Number(value) : undefined;
export function CashRegisterScreen() { const router = useRouter(); const { state } = useSession(); const query = useCurrentCashRegister(); const read = state.status === 'authenticated' && can(state.permissions, 'CAJA_CONSULTAR'); const open = state.status === 'authenticated' && can(state.permissions, 'CAJA_ABRIR'); const close = state.status === 'authenticated' && can(state.permissions, 'CAJA_CERRAR'); if (!read) return <Screen title="Caja"><AccessDeniedState /></Screen>; if (query.isPending) return <Screen title="Caja"><LoadingState message="Consultando caja…" /></Screen>; if (query.isError) return <Screen title="Caja"><ErrorState onRetry={() => void query.refetch()} traceId={query.error instanceof ApiError ? query.error.traceId : undefined} /></Screen>; if (!query.data) return <Screen title="Caja"><Text style={styles.title}>No hay una caja abierta</Text>{open ? <AppButton label="Abrir caja" onPress={() => router.push('./open')} /> : null}</Screen>; const cash = query.data; return <Screen title="Caja" subtitle={cash.branchName ?? 'Sucursal actual'}><View style={styles.card}><Text style={styles.title}>Caja abierta · MXN</Text><Text style={styles.text}>Inicial: ${cash.initialCash.toFixed(2)}</Text><Text style={styles.text}>Esperado: ${cash.expectedCash.toFixed(2)}</Text></View>{close ? <AppButton label="Cerrar caja" variant="danger" onPress={() => router.push('./close')} /> : null}<AppButton label="Actualizar" variant="secondary" loading={query.isRefetching} onPress={() => void query.refetch()} /></Screen>; }
export function OpenCashRegisterScreen() { const router = useRouter(); const { isOnline } = useNetworkStatus(); const mutation = useOpenCashRegister(); const [input, setInput] = useState(''); const parsed = money(input); return <Screen title="Abrir caja" subtitle="Moneda: MXN"><OfflineBanner visible={!isOnline} /><TextField label="Monto inicial" value={input} onChangeText={setInput} keyboardType="decimal-pad" /><AppButton label="Confirmar apertura" disabled={!isOnline || parsed === undefined} loading={mutation.isPending} onPress={() => mutation.mutate({ openingAmount: parsed!, currency: 'MXN' }, { onSuccess: () => router.back() })} />{mutation.isError ? <ErrorState traceId={mutation.error instanceof ApiError ? mutation.error.traceId : undefined} /> : null}</Screen>; }
export function CloseCashRegisterScreen() { const router = useRouter(); const { isOnline } = useNetworkStatus(); const cash = useCurrentCashRegister(); const mutation = useCloseCashRegister(); const [input, setInput] = useState(''); const [closed, setClosed] = useState<CashRegisterSnapshot>(); const parsed = money(input); if (cash.isPending) return <Screen title="Cerrar caja"><LoadingState message="Consultando caja…" /></Screen>; const current = cash.data; if (!current && !closed) return <Screen title="Cerrar caja"><ErrorState message="No existe una caja abierta para cerrar." /></Screen>; if (closed) return <Screen title="Cierre de caja confirmado"><View style={styles.card}><Text style={styles.text}>Contado: ${closed.countedCash?.toFixed(2) ?? 'No disponible'} MXN</Text><Text style={styles.text}>Diferencia: ${closed.difference?.toFixed(2) ?? 'No disponible'} MXN</Text></View><AppButton label="Volver a caja" onPress={() => router.back()} /></Screen>; return <Screen title="Cerrar caja"><OfflineBanner visible={!isOnline} /><Text style={styles.text}>Esperado: ${current!.expectedCash.toFixed(2)} MXN</Text><TextField label="Monto contado" value={input} onChangeText={setInput} keyboardType="decimal-pad" /><AppButton label="Confirmar cierre" variant="danger" disabled={!isOnline || parsed === undefined} loading={mutation.isPending} onPress={() => mutation.mutate({ cashRegisterId: current!.id, countedAmount: parsed!, currency: 'MXN' }, { onSuccess: setClosed })} />{mutation.isError ? <ErrorState traceId={mutation.error instanceof ApiError ? mutation.error.traceId : undefined} /> : null}</Screen>; }
const styles = StyleSheet.create({ card: { gap: spacing[2], padding: spacing[4], borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, title: { ...typography.title, color: colors.text }, text: { ...typography.body, color: colors.text } });
